### ISSUE TITLE
Enhancing the Project Code of Conduct

### ISSUE THREAD

**Issue by nkoik** [TvonSween/sem-one#3]
**As a** member of the project team, 

**I want** to ensure that we enhance and clearly define the code of conduct so that every team member understands the expected behaviours and ethical standards. 

**This will** lead to a more respectful, inclusive, and productive working environment.

**Comment by nkoik** [comment]
As a team, we should enhance and define the code of conduct for the project

**Comment by nkoik** [comment]
We can also create a CODE_OF_CONDUCT.md file in the root level of the project @napierkhinds

**Comment by napierkhinds** [comment]
Great suggestion, I will do that @nkoik.
